watch_config: true
bars:
  main_bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    dimensions:
      width: "100%"
      height: 30
    widgets:
      left: ["komorebi_workspaces"]
      center: ["clock"]
      right: ["cpu", "memory", "battery"]

widgets:
  komorebi_workspaces:
    type: "komorebi_workspaces"
    options:
      label_offline: "K"
      label_workspace: "{index}"
      label_workspace_active: "{index}"
      label_workspace_empty: "{index}"
  clock:
    type: "clock"
    options:
      label: "{%a %d %b | %H:%M:%S}"
  cpu:
    type: "cpu"
  memory:
    type: "memory"
  battery:
    type: "battery"
