watch_config: true
bars:
  main_bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    dimensions:
      width: "100%"
      height: 30
    window_flags:
      windows_app_bar: true
      always_on_top: true
    widgets:
      left: ["komorebi_workspaces", "taskbar"]
      center: []
      right: ["cpu", "memory", "battery", "clock"]

widgets:
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "K"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d %b | %H:%M:%S}"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "CPU: {info[histograms][cpu_percent]}%"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "RAM: {virtual_mem_percent}%"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "BAT: {percent}%"
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      show_only_visible: true
      strict_filtering: true
      icon_size: 14
      title_label:
        enabled: true
        show: "always"
        max_length: 20
