windowrule = match:class ^([Mm]pv|vlc)$, tag +multimedia_video
windowrule = match:class ^(nm-applet|nm-connection-editor|blueman-manager|org.gnome.FileRoller)$, tag +settings
windowrule = match:class ^(org.gnome.DiskUtility|wihotspot(-gui)?)$, tag +settings
windowrule = match:class ^(org.gnome.SystemMonitor)$, tag +viewer
windowrule = match:class ^(org.gnome.Evince)$, tag +viewer
windowrule = match:class ^(eog|org.gnome.Loupe)$, tag +viewer
