# APPLICATIONS BLUR & OPACITY & FLOATING & SIZE
windowrule = match:tag multimedia_video*, no_blur 1, opacity 1.0, float 1, size 900 506
windowrule = match:tag settings*, opacity 0.8, float 1
windowrule = match:tag viewer*, float 1
windowrule = match:class ^(org.gnome.Nautilus)$, opacity 0.8
windowrule = match:class ^(gedit|org.gnome.TextEditor|mousepad)$, opacity 0.9
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, opacity 0.9, float 1, size 50% 60%
windowrule = match:class ^(kitty)$, opacity 0.9
windowrule = match:class ^(discord|vesktop|org.telegram.desktop)$, opacity 0.85 override 0.7 override 1 override
windowrule = match:class ^(Spotify)$, opacity 0.8 override 0.6 override 1 override
windowrule = match:class ^(zen)$, opacity 0.9 override 0.7 override 1 override

# LAYER RULES
layerrule = match:namespace ^(waybar)$, blur 1, ignore_alpha 0.5
layerrule = match:namespace ^(notif.*)$, ignore_alpha 0.5
layerrule = match:namespace ^(logout_dialog)$, blur 1

# SWAYNC BLUR & XRAY
layerrule = match:namespace ^(swaync-control-center)$, blur 1, ignore_alpha 0.5, xray 0
layerrule = match:namespace ^(swaync-notification-window)$, blur 1, ignore_alpha 0.5, xray 0

# Ignore maximize requests from apps.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, no_focus 1

# POP UPS AND DIALOGUES
windowrule = match:title ^(Save As|Save a File|Pick Files)$, float 1, size 50% 60%, center 1
windowrule = match:initial_title ^(Open Files)$, float 1, size 70% 60%
