# APPLIACTIONS BLUR
windowrule = noblur 1, match:tag:(multimedia_video*)
windowrule = opacity 1.0, match:tag:(multimedia_video*)
windowrule = opacity 0.8, match:tag:(settings*)
windowrule = opacity 0.8, match:class:(org.gnome.Nautilus)
windowrule = opacity 0.9, match:class:(gedit|org.gnome.TextEditor|mousepad)
windowrule = opacity 0.9, match:class:(org.pulseaudio.pavucontrol)
windowrule = opacity 0.9, match:class:(kitty)
windowrule = opacity 0.85 override 0.7 override 1 override, match:class:(discord|vesktop|org.telegram.desktop)
windowrule = opacity 0.8 override 0.6 override 1 override, match:class:(Spotify)
windowrule = opacity 0.9 override 0.7 override 1 override, match:class:(zen)

# LAYER RULES
layerrule = blur 1, match:namespace:(waybar)
layerrule = ignorealpha 0.5, match:namespace:(waybar)
layerrule = ignorealpha 0.5, match:namespace:(notif*)
layerrule = blur 1, match:namespace:(logout_dialog)

# SWAYNC BLUR & XRAY
layerrule = blur 1, match:namespace:(swaync-control-center)
layerrule = blur 1, match:namespace:(swaync-notification-window)
layerrule = ignorezero 1, match:namespace:(swaync-control-center)
layerrule = ignorezero 1, match:namespace:(swaync-notification-window)
layerrule = ignorealpha 0.5, match:namespace:(swaync-control-center)
layerrule = ignorealpha 0.5, match:namespace:(swaync-notification-window)
layerrule = xray 0, match:namespace:(swaync-control-center)
layerrule = xray 0, match:namespace:(swaync-notification-window)

#FLOAT
windowrule = float 1, match:tag:(settings*)
windowrule = float 1, match:tag:(viewer*)
windowrule = float 1, match:tag:(multimedia_video*)
windowrule = size 900 506, match:tag:(multimedia_video*)
windowrule = float 1, match:class:(org.pulseaudio.pavucontrol)
windowrule = size 50% 60%, match:class:(org.pulseaudio.pavucontrol)

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, match:class:(.*)

# Fix some dragging issues with XWayland
windowrule = nofocus 1, match:class:(^$), match:title:(^$), match:xwayland 1, match:floating 1, match:fullscreen 0, match:pinned 0

# POP UPS AND DIALOGUES
windowrule = float 1, match:title:(Save As|Save a File|Pick Files)
windowrule = size 50% 60%, match:title:(Save As|Save a File|Pick Files)
windowrule = center 1, match:title:(Save As|Save a File|Pick Files)

windowrule = float 1, match:initialTitle:(Open Files)
windowrule = size 70% 60%, match:initialTitle:(Open Files)
