# Generated by modules/theming/matugen (matugen palette post-processing) — do not edit
# shellcheck shell=bash
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --highlight-line --color=pointer:@@ACCENT@@,marker:@@ACCENT@@,prompt:@@ACCENT@@,info:@@TERTIARY@@,hl:@@TERTIARY@@,hl+:@@TERTIARY@@,bg+:@@SELECTION_BG@@'
# atuin (modules/shell/atuin/fzf-style.patch) が選択行の背景色に使う。
export ATUIN_SELECTION_BG='@@SELECTION_BG@@'
