-- Generated by Matugen — do not edit
return {
  accent = "{{colors.primary.default.hex}}",
  tertiary = "{{colors.tertiary.default.hex}}",
  secondary = "{{colors.secondary.default.hex}}",
  text = "{{colors.on_surface.default.hex}}",
  muted = "{{colors.on_surface_variant.default.hex}}",
  surface = "{{colors.surface_container_high.default.hex}}",
  on_accent = "{{colors.surface.default.hex}}",
  error = "{{colors.error.default.hex}}",
}
