# Generated by Matugen — do not edit
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --color=pointer:{{colors.primary.default.hex}},marker:{{colors.primary.default.hex}},prompt:{{colors.primary.default.hex}},info:{{colors.tertiary.default.hex}},hl:{{colors.tertiary.default.hex}},hl+:{{colors.tertiary.default.hex}}'
