# Generated by Matugen — do not edit
# shellcheck shell=bash
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --highlight-line --color=pointer:{{colors.primary.default.hex}},marker:{{colors.primary.default.hex}},prompt:{{colors.primary.default.hex}},info:{{colors.tertiary.default.hex}},hl:{{colors.tertiary.default.hex}},hl+:{{colors.tertiary.default.hex}},bg+:#2a2a2a'
