# Starship performance optimizations for WSL
scan_timeout = 20
command_timeout = 500

palette = "matugen"

format = """
$os\
$directory\
[](fg:accent bg:dark)\
$git_branch\
$git_status\
[](fg:dark)\
\n$character\
"""

right_format = """$cmd_duration$time"""

add_newline = true

[os]
disabled = false
style = "fg:on_accent bg:accent_sub bold"
format = "[ $symbol]($style)[](fg:accent_sub bg:accent)"

[os.symbols]
Alpinelinux = " "
Amzn = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
NixOS = " "
OpenSUSE = " "
OracleLinux = "󰆚 "
Redhat = " "
RedHatedit = " "
RockyLinux = " "
SUSE = " "
Ubuntu = " "
Windows = " "
WSL = " "

[username]
disabled = true

[hostname]
disabled = true

[fill]
symbol = ' '

[directory]
style = "fg:on_accent bg:accent bold"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"
read_only = ' 󰌾 '
read_only_style = 'fg:on_accent bg:accent'
format = '[ $path ]($style)[$read_only]($read_only_style)'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
disabled = true
[gcloud]
disabled = true

[git_branch]
symbol = ""
style = "bg:dark"
format = '[[ $symbol $branch ](fg:accent bg:dark)]($style)'

[git_status]
style = "bg:dark"
format = '[[($all_status$ahead_behind )](fg:accent bg:dark)]($style)'

[cmd_duration]
min_time = 1
style = 'fg:accent_sub'
format = "[[  ](fg:muted) $duration]($style)"

[time]
disabled = false
time_format = "%R"
format = '[[  $time ](fg:muted)]($style)'

[character]
success_symbol = "[❯](bold accent_sub)"
error_symbol = "[❯](bold accent_sub)"
vicmd_symbol = "[❯](bold #8e8e8e)"

# MATUGEN:START
[palettes.matugen]
accent = "{{colors.primary.default.hex}}"
accent_sub = "{{colors.tertiary.default.hex}}"
secondary = "{{colors.secondary.default.hex}}"
muted = "{{colors.on_surface_variant.default.hex}}"
dark = "{{colors.surface_container_high.default.hex}}"
on_accent = "{{colors.surface.default.hex}}"
# MATUGEN:END
